In [1]:
import pandas as pd
import numpy as np

In [2]:
data1 = pd.read_excel(r'D:\办公文件\编程\实战项目\深圳二手房房价分析及预测\data\House_Price_SZ3933\szfj_baoan.xls')
data2 = pd.read_excel(r'D:\办公文件\编程\实战项目\深圳二手房房价分析及预测\data\House_Price_SZ3933\szfj_dapengxinqu.xls')
data3 = pd.read_excel(r'D:\办公文件\编程\实战项目\深圳二手房房价分析及预测\data\House_Price_SZ3933\szfj_futian.xls')
data4 = pd.read_excel(r'D:\办公文件\编程\实战项目\深圳二手房房价分析及预测\data\House_Price_SZ3933\szfj_guangming.xls')
data5 = pd.read_excel(r'D:\办公文件\编程\实战项目\深圳二手房房价分析及预测\data\House_Price_SZ3933\szfj_longgang.xls')
data6 = pd.read_excel(r'D:\办公文件\编程\实战项目\深圳二手房房价分析及预测\data\House_Price_SZ3933\szfj_longhua.xls')
data7 = pd.read_excel(r'D:\办公文件\编程\实战项目\深圳二手房房价分析及预测\data\House_Price_SZ3933\szfj_luohu.xls')
data8 = pd.read_excel(r'D:\办公文件\编程\实战项目\深圳二手房房价分析及预测\data\House_Price_SZ3933\szfj_nanshan.xls')
data9 = pd.read_excel(r'D:\办公文件\编程\实战项目\深圳二手房房价分析及预测\data\House_Price_SZ3933\szfj_pingshan.xls')
data10 = pd.read_excel(r'D:\办公文件\编程\实战项目\深圳二手房房价分析及预测\data\House_Price_SZ3933\szfj_yantian.xls')

In [3]:
data = pd.DataFrame(columns = data1.columns)

In [4]:
data = data.append(data1)
data = data.append(data2)
data = data.append(data3)
data = data.append(data4)
data = data.append(data5)
data = data.append(data6)
data = data.append(data7)
data = data.append(data8)
data = data.append(data9)
data = data.append(data10)
data

Unnamed: 0 district roomnum hall    AREA C_floor floor_num school subway  \
0     228757275    baoan       3    2   89.30  middle        31      0      0   
1     228757221    baoan       4    2  127.00    high        31      0      0   
2     228267986    baoan       1    1   28.00     low        39      0      0   
3     228879860    baoan       1    1   28.00  middle        30      0      0   
4     228521057    baoan       2    2   78.00  middle         8      1      1   
...         ...      ...     ...  ...     ...     ...       ...    ...    ...   
1487  228604127  yantian       1    0   29.90  middle        10      1      0   
1488  227865185  yantian       1    0   29.89  middle         8      1      0   
1489  227990827  yantian       1    0   28.86    high         8      0      0   
1490  226997909  yantian       1    1   26.29    high        18      1      0   
1491  226378735  yantian       1    0   18.86     low        18      0      0   

      per_price  
0        7.0773  
1        6.9291  
2        3.9286  
3        3.3568  
4        5.0769  
...         ...  
1487     3.8796  
1488     4.0147  
1489     5.0243  
1490     4.9068  
1491     4.2948  

[18514 rows x 10 columns]

In [5]:
data.to_csv(r'D:\办公文件\编程\实战项目\深圳二手房房价分析及预测\data\House_Price_SZ3933\data.csv',index=False)

In [6]:
# data.drop(columns = data.columns[0],inplace = True)
data = data.reset_index(drop = True)
data

Unnamed: 0 district roomnum hall    AREA C_floor floor_num school  \
0      228757275    baoan       3    2   89.30  middle        31      0   
1      228757221    baoan       4    2  127.00    high        31      0   
2      228267986    baoan       1    1   28.00     low        39      0   
3      228879860    baoan       1    1   28.00  middle        30      0   
4      228521057    baoan       2    2   78.00  middle         8      1   
...          ...      ...     ...  ...     ...     ...       ...    ...   
18509  228604127  yantian       1    0   29.90  middle        10      1   
18510  227865185  yantian       1    0   29.89  middle         8      1   
18511  227990827  yantian       1    0   28.86    high         8      0   
18512  226997909  yantian       1    1   26.29    high        18      1   
18513  226378735  yantian       1    0   18.86     low        18      0   

      subway  per_price  
0          0     7.0773  
1          0     6.9291  
2          0     3.9286  
3          0     3.3568  
4          1     5.0769  
...      ...        ...  
18509      0     3.8796  
18510      0     4.0147  
18511      0     5.0243  
18512      0     4.9068  
18513      0     4.2948  

[18514 rows x 10 columns]

In [7]:
# 构造特征
features = data.drop(columns = data.columns[0])
features

district roomnum hall    AREA C_floor floor_num school subway  per_price
0        baoan       3    2   89.30  middle        31      0      0     7.0773
1        baoan       4    2  127.00    high        31      0      0     6.9291
2        baoan       1    1   28.00     low        39      0      0     3.9286
3        baoan       1    1   28.00  middle        30      0      0     3.3568
4        baoan       2    2   78.00  middle         8      1      1     5.0769
...        ...     ...  ...     ...     ...       ...    ...    ...        ...
18509  yantian       1    0   29.90  middle        10      1      0     3.8796
18510  yantian       1    0   29.89  middle         8      1      0     4.0147
18511  yantian       1    0   28.86    high         8      0      0     5.0243
18512  yantian       1    1   26.29    high        18      1      0     4.9068
18513  yantian       1    0   18.86     low        18      0      0     4.2948

[18514 rows x 9 columns]

In [8]:
features.dtypes

district      object
roomnum       object
hall          object
AREA         float64
C_floor       object
floor_num     object
school        object
subway        object
per_price    float64
dtype: object

In [9]:
# one-hot
features = pd.get_dummies(features)
features.head(5)

AREA  per_price  district_baoan  district_dapengxinqu  district_futian  \
0   89.3     7.0773               1                     0                0   
1  127.0     6.9291               1                     0                0   
2   28.0     3.9286               1                     0                0   
3   28.0     3.3568               1                     0                0   
4   78.0     5.0769               1                     0                0   

   district_guangming  district_longgang  district_longhua  district_luohu  \
0                   0                  0                 0               0   
1                   0                  0                 0               0   
2                   0                  0                 0               0   
3                   0                  0                 0               0   
4                   0                  0                 0               0   

   district_nanshan  ...  floor_num_73  floor_num_75  floor_num_80  \
0                 0  ...             0             0             0   
1                 0  ...             0             0             0   
2                 0  ...             0             0             0   
3                 0  ...             0             0             0   
4                 0  ...             0             0             0   

   floor_num_88  floor_num_89  floor_num_90  school_0  school_1  subway_0  \
0             0             0             0         1         0         1   
1             0             0             0         1         0         1   
2             0             0             0         1         0         1   
3             0             0             0         1         0         1   
4             0             0             0         0         1         0   

   subway_1  
0         0  
1         0  
2         0  
3         0  
4         1  

[5 rows x 102 columns]

In [10]:
# 标签
labels = np.array(features['per_price'])
# 在特征中去掉标签
features= features.drop('per_price', axis = 1)
# 名字单独保存一下，以备后患
feature_list = list(features.columns)
# 转换成合适的格式
features = np.array(features)

In [11]:
features.shape

(18514, 101)

In [12]:
labels

array([7.0773, 6.9291, 3.9286, ..., 5.0243, 4.9068, 4.2948])

In [13]:
features

array([[ 89.3 ,   1.  ,   0.  , ...,   0.  ,   1.  ,   0.  ],
       [127.  ,   1.  ,   0.  , ...,   0.  ,   1.  ,   0.  ],
       [ 28.  ,   1.  ,   0.  , ...,   0.  ,   1.  ,   0.  ],
       ...,
       [ 28.86,   0.  ,   0.  , ...,   0.  ,   1.  ,   0.  ],
       [ 26.29,   0.  ,   0.  , ...,   1.  ,   1.  ,   0.  ],
       [ 18.86,   0.  ,   0.  , ...,   0.  ,   1.  ,   0.  ]])

In [14]:
# 归一化数据
from sklearn import preprocessing

input_features = preprocessing.StandardScaler().fit_transform(features)
input_features

array([[-0.12199029,  3.71474905, -0.20346863, ..., -1.19328662,
         1.00835291, -1.00835291],
       [ 0.65422789,  3.71474905, -0.20346863, ..., -1.19328662,
         1.00835291, -1.00835291],
       [-1.38411694,  3.71474905, -0.20346863, ..., -1.19328662,
         1.00835291, -1.00835291],
       ...,
       [-1.36641011, -0.26919719, -0.20346863, ..., -1.19328662,
         1.00835291, -1.00835291],
       [-1.41932472, -0.26919719, -0.20346863, ...,  0.83802163,
         1.00835291, -1.00835291],
       [-1.57230353, -0.26919719, -0.20346863, ..., -1.19328662,
         1.00835291, -1.00835291]])

In [15]:
# 切分训练集与测试集
from sklearn.model_selection import train_test_split

x_tr,x_val,y_tr,y_val=train_test_split(input_features,labels,test_size=0.2)

In [16]:
y_tr

array([13.5145,  4.4045,  5.3901, ...,  4.9589,  3.8384,  6.8096])

In [17]:
# 使用TensorDataset和DataLoader来简化数据处理
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader
import torch

x_tr, y_tr, x_val, y_val = map(torch.tensor, (x_tr, y_tr, x_val, y_val))  #需要转换成tensor的形式才能继续建模

tr_ds = TensorDataset(x_tr, y_tr)     # 将数据转化成tensor的形式
val_ds = TensorDataset(x_val, y_val)

In [18]:
# 分开取数据集
def get_data(train_ds, valid_ds, bs):    # bs为batch_size
    return (
        DataLoader(train_ds, batch_size=bs, shuffle=True),
        DataLoader(valid_ds, batch_size=bs * 2),
    )

In [19]:
# 构造损失函数
import torch.nn.functional as F

def loss_batch(model, loss_func, xb, yb, opt=None):
    loss = loss_func(model(xb), yb)
    if opt is not None:
        loss.backward()
        opt.step()
        opt.zero_grad()

    return loss.item(), len(xb)

In [20]:
# 定义模型
from torch import nn

class DNN(nn.Module):
    def __init__(self,input_size,output_size):
        super().__init__()
        self.hidden1 = nn.Linear(input_size,256)
        self.hidden2 = nn.Linear(256,512)
        self.hidden3 = nn.Linear(512,256)
        self.out = nn.Linear(256,output_size)
        
    def forward(self,x):
        x = F.relu(self.hidden1(x))
        x = F.relu(self.hidden2(x))
        x = F.relu(self.hidden3(x))
        x = self.out(x)
        
        return x

In [21]:
# 实例化模型以及调用优化器
from torch import optim
def get_model(input_size,output_size):
    model = DNN(input_size,output_size)
    return model, optim.Adam(model.parameters(), lr=0.0001)

In [22]:
# 模型训练以及验证
def fit(steps, model, loss_func, opt, train_dl, valid_dl):
    for step in range(steps):
        model.train()
        for xb, yb in train_dl:         # 每一个batch每一个batch去取
            loss_batch(model, loss_func, xb.float() , yb.float() , opt)

        model.eval()
        with torch.no_grad():
            losses, nums = zip(
                *[loss_batch(model, loss_func, xb.float() , yb.float() ) for xb, yb in valid_dl]
            )
        val_loss = np.sum(np.multiply(losses, nums)) / np.sum(nums)
        print('当前step:'+str(step), '验证集损失：'+str(val_loss))

In [25]:
input_size = input_features.shape[1]
output_size = 1
loss_func = torch.nn.MSELoss(reduction='mean') # 损失函数
bs = 5000  # a mini-batch

In [27]:
train_dl, valid_dl = get_data(tr_ds, val_ds, bs)
model, opt = get_model(input_size,output_size)
fit(1000, model, loss_func, opt, train_dl, valid_dl)

当前step:0 验证集损失：45.05975341796875
当前step:1 验证集损失：44.167118072509766
当前step:2 验证集损失：43.27928924560547
当前step:3 验证集损失：42.35620880126953
当前step:4 验证集损失：41.363121032714844
当前step:5 验证集损失：40.26817321777344
当前step:6 验证集损失：39.04670715332031
当前step:7 验证集损失：37.67987823486328
当前step:8 验证集损失：36.153778076171875
当前step:9 验证集损失：34.46405792236328
当前step:10 验证集损失：32.616607666015625
当前step:11 验证集损失：30.62986183166504
当前step:12 验证集损失：28.541133880615234
当前step:13 验证集损失：26.40146255493164
当前step:14 验证集损失：24.287687301635742
当前step:15 验证集损失：22.28310775756836
当前step:16 验证集损失：20.49319076538086
当前step:17 验证集损失：19.00963592529297
当前step:18 验证集损失：17.910097122192383
当前step:19 验证集损失：17.194717407226562
当前step:20 验证集损失：16.800973892211914
当前step:21 验证集损失：16.58660316467285
当前step:22 验证集损失：16.380474090576172
当前step:23 验证集损失：16.110376358032227
当前step:24 验证集损失：15.773102760314941
当前step:25 验证集损失：15.409124374389648
当前step:26 验证集损失：15.06698989868164
当前step:27 验证集损失：14.77227783203125
当前step:28 验证集损失：14.512791633605957
当前step:29 